# Generated by Django 4.0.4 on 2022-05-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='week_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
