# Generated by Django 4.0.4 on 2022-06-02 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_week_week_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='time_between_sessions',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
